import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import GlobalProvider from './provider/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gulf Auction',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
      
      <GlobalProvider>
      <Navbar/>
        {children}
      <Footer/>
      </GlobalProvider>
        </body>
    </html>
  )
}
